### ISSUE TITLE
Auto discover staging directory

### ISSUE THREAD

**Issue by DavideFranchioni** [pitdive/haproxy_config#1]
Hello, 

I think the script could find the survey.csv, config, staging directory automatically.
I use those variables in my bash script to figure-out the right folder automatically:
`STAGING_DIR=$(grep installscript /opt/cloudian/conf/cloudianservicemap.json | tr '"' '\n' | grep cloudianInstall.sh | sed  's/\/cloudianInstall.sh//' | head -1)
CONF=$(grep INSTALL_SSH_KEY_FILE $STAGING_DIR/CloudianInstallConfiguration.txt | cut -d "=" -f2 | sed 's/.\///')
`
I think you can to the same in Python in your script.

Best Regards,
Davide :)

**Comment by pitdive** [comment]
Hi Davide,
I have included this feature in the new version I will release it soon.
